name = "reach"
main = "src/worker.ts"
compatibility_date = "2026-10-03"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "reach"
database_id = "3be84630-6207-4138-8ac5-1654aed293b4"
migrations_dir = "migrations"

[observability]
enabled = true
