name = "reach"
main = "src/worker.ts"
compatibility_date = "2026-10-03"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
ADMIN_USER_IDS = "7918162941"

[[d1_databases]]
binding = "DB"
database_name = "reach"
database_id = "3be84630-6207-4138-8ac5-1654aed293b4"
migrations_dir = "migrations"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1
persist = true

[observability.traces]
enabled = false
